name: Run LLM Tests (Manual)

on:
  workflow_dispatch:
    inputs:
      test_filter:
        description: 'Test filter (e.g., test_character_info.py)'
        required: false
        default: ''

jobs:
  test-llm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run LLM tests
      run: |
        echo "⚠️  Note: These tests require a local LLM server at localhost:11434"
        echo "If no server is available, tests will fail with connection errors."
        echo ""
        if [ -n "${{ github.event.inputs.test_filter }}" ]; then
          python -m pytest -v -m "llm" tests/${{ github.event.inputs.test_filter }}
        else
          python -m pytest -v -m "llm"
        fi
      env:
        PYTHONPATH: ${{ github.workspace }}

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: llm-test-results
        path: |
          .pytest_cache/
          *.log